@BaseUrl = http://localhost:5256

GET {{BaseUrl}}/api/v1/todos
Accept: application/json

###

GET {{BaseUrl}}/api/v1/todos?category=work
Accept: application/json

###

GET {{BaseUrl}}/openapi/v1.json

###